// Rules of files generated by models (ADR-028, `FilesService.saveGenerated`): only raster images of
// `GENERATED_IMAGE_MIME_TYPES` (PNG, JPEG, WebP, GIF) whose magic bytes match the declared type, at most
// `LIMITS.generatedImageBytes`, named like uploads (the extension of the type added when the name has none). Anything
// else is refused; callers count a refused file as dropped (the `generated-file-dropped` notice, `ImageService`
// `dropped`).
import type { GeneratedImageMimeType } from '@harness-forge/shared'
import { GENERATED_IMAGE_MIME_TYPES, HarnessError, LIMITS, validationError } from '@harness-forge/shared'
import { sanitizeFileName } from './names.ts'
import { canonicalMime, extensionForMime, sniffBinaryType } from './sniff.ts'

/** A type a generated image may be stored as. */
export function isGeneratedImageMime(type: string): type is GeneratedImageMimeType {
  return (GENERATED_IMAGE_MIME_TYPES as readonly string[]).includes(type)
}

/** The `payload_too_large` of a generated image above `LIMITS.generatedImageBytes`. */
export function generatedImageTooLarge(): HarnessError {
  return new HarnessError({
    code: 'payload_too_large',
    message: `Generated images are limited to ${LIMITS.generatedImageBytes / 1024 / 1024} MB.`,
    details: { limitBytes: LIMITS.generatedImageBytes },
  })
}

function refused(path: 'mediaType' | 'data', message: string): HarnessError {
  return validationError([{ path: [path], message, code: 'custom' }], message)
}

/**
 * The type a generated file is stored as, or throws: the canonical `mediaType` (parameters dropped, aliases such as
 * `image/jpg` resolved) must be a `GENERATED_IMAGE_MIME_TYPES` entry (else `validation_error` on `mediaType`), the bytes
 * at most `LIMITS.generatedImageBytes` (else `payload_too_large`) and their magic bytes must match the type (else
 * `validation_error` on `data`).
 */
export function checkGeneratedFile(data: unknown, mediaType: unknown): GeneratedImageMimeType {
  const type = canonicalMime(typeof mediaType === 'string' ? mediaType : undefined)
  if (!isGeneratedImageMime(type)) {
    const shown = type === '' ? 'a file without a valid type' : `"${type}"`
    throw refused('mediaType', `Generated files are stored only as PNG, JPEG, WebP or GIF images, not ${shown}.`)
  }
  if (!(data instanceof Uint8Array))
    throw refused('data', 'The generated file has no bytes.')
  if (data.byteLength > LIMITS.generatedImageBytes)
    throw generatedImageTooLarge()
  if (sniffBinaryType(data) !== type)
    throw refused('data', `The generated image does not match its type (${type}).`)
  return type
}

/** The stored name of a generated file: sanitized like an upload name, with the extension of `mime` when it has none. */
export function generatedFileName(raw: unknown, mime: string): string {
  const name = sanitizeFileName(typeof raw === 'string' ? raw : '', mime)
  const dot = name.lastIndexOf('.')
  if (dot > 0 && dot < name.length - 1)
    return name
  const stem = dot === name.length - 1 ? name.slice(0, -1) : name
  return sanitizeFileName(`${stem}${extensionForMime(mime)}`, mime)
}
