// @harness-forge/plugin-sdk: the public plugin contract (docs/PLUGINS.md section 9). Plugin authors import everything
// from here. The plugin data shapes and enums are defined in @harness-forge/shared (ADR-018) and re-exported unchanged.
export { definePlugin } from './define-plugin.ts'
export { settingsValuesSchema } from './settings.ts'
export type { SettingsValuesSchemaOptions } from './settings.ts'
export type {
  AgentDefinition,
  CommandDefinition,
  CommandRunInput,
  CommandRunResult,
  Disposable,
  GeneratedImageFile,
  HookChatContext,
  HookHandler,
  HookMap,
  HookName,
  HostAi,
  ImageGenerateOptions,
  ImageGenerateResult,
  ImageParamsRequest,
  ImageParamsResult,
  KV,
  Logger,
  PluginContext,
  PluginImagesApi,
  PluginModule,
  ProviderDefinition,
  ProviderOptions,
  ProviderRuntime,
  ReasoningLevel,
  ReasoningParams,
  SkillDefinition,
  ToolCallContext,
  ToolDefinition,
  ToolPolicyFunction,
  ToolResultOutput,
  ToolWorkspace,
  ToolWorkspaceAccess,
  TranscriptionHints,
} from './types.ts'
export { PLUGIN_API_VERSION } from './version.ts'
export {
  apiFormatSchema,
  credentialFieldSchema,
  declarativeCommandSchema,
  declarativeProviderSchema,
  harnessErrorActionSchema,
  harnessErrorCodeSchema,
  harnessErrorInitSchema,
  mcpServerDeclSchema,
  modelInfoSchema,
  pluginKindSchema,
  pluginManifestBaseSchema,
  pluginManifestSchema,
  pluginPermissionSchema,
  pluginSourceSchema,
  pluginStateSchema,
  reasoningEffortSchema,
  reasoningStyleSchema,
  settingsPropertySchema,
  settingsSchemaSchema,
  toolModeSchema,
  toolPolicySchema,
} from '@harness-forge/shared'
export type {
  ApiFormat,
  CredentialField,
  DeclarativeAgent,
  DeclarativeCommand,
  DeclarativeProvider,
  DeclarativeSkill,
  HarnessErrorAction,
  HarnessErrorCode,
  HarnessErrorInit,
  ImageAspectRatio,
  McpServerDecl,
  ModelInfo,
  ModelKind,
  PluginKind,
  PluginManifest,
  PluginPermission,
  PluginSource,
  PluginState,
  ReasoningEffort,
  ReasoningStyle,
  SettingsProperty,
  SettingsSchema,
  ToolMode,
  ToolPolicy,
} from '@harness-forge/shared'
